[workspace]
members = [
  "rlay_ontology",
  "rlay_ontology_stdweb"
]

[patch.crates-io]
# see https://github.com/ipld/rust-cid/pull/9
cid = { git = 'https://github.com/hobofan/rust-cid', branch = 'feat/unknown' }

