[package]
name = "rlay_ontology"
version = "0.2.1"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]

[lib]
name = "rlay_ontology"
path = "src/lib.rs"

[[example]]
name = "example_hashes"
path = "src/bin.rs"
required-features = ["examples"]

[dependencies]
prost = "0.3.0"
bytes = "0.4.6"
prost-derive = "0.3.0"
multihash = "0.8.0"
cid = "0.2.3"
itertools = "0.7.6"
multibase = "0.6.0"
failure = "0.1.1"
integer-encoding = "1.0"
serde = "1.0.66"
serde_derive = "1.0.66"
rustc-hex = "2.0.1"
serde_cbor = "0.9.0"
serde_json = { version = "1", optional = true }
varint = { git = "https://github.com/sirkibsirkib/serde_varint" }
serde_bytes = "0.10.4"

# feature web3_compat
web3 = { version = "0.4.0", optional = true }

# feature pwasm
pwasm-abi = { version = "0.1", optional = true }

[build-dependencies]
prost-build = "0.3.0"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.27"
heck = "0.3.0"
syn = { version = "0.15", features = ["full", "extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4.20"

[features]
default = ["std"]
std = []

web3_compat = ["web3"]
pwasm = ["pwasm-abi"]

examples = ["serde_json"]
